---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

# Default state for all rules
default: false

#################
# Rules by tags #
#################
code-fence-style:
  style: "backtick"
fenced-code-language: true    # Fenced code blocks should have a language specified
heading-start-left: true      # Headings must start at the beginning of the line
heading-style:
  style: "atx"
hr-style: true                # Horizontal rule style
list-indent: true             # Inconsistent indentation for list items at the same level
no-empty-links: true
no-missing-space-atx: true    # No space after hash on atx style heading
no-reversed-links: true
no-space-in-code: true
no-space-in-emphasis: true
single-h1: { "front_matter_title" : "" }  # Only one h1 heading per file
no-alt-text: true #require alt-text
