---
###########################
###########################
## Deployment AI generation testing ##
###########################
###########################

name: Hackathon Deployment Request

######################################################
# Start the job on a "deployment" to hackathon-test or other branch #
######################################################

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target branch to send PR to (e.g., main, stage, etc)"
        type: string
        required: false
        default: "hackathon-test"

###############
# Set the Job #
###############

jobs:
  ai-metadata-update:
    name: AI Metadata Update on Deployment
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/ai-deploy-metadata.yml@app-builder-test
    with:
      FILE_NAME: "all_pages_content.txt"
      TARGET_BRANCH: ${{ inputs.target_branch }}
    secrets:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}

  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Lint
        run: npx --yes github:AdobeDocs/adp-devsite-utils#add-lint-check runLint -v
