---
###########################
###########################
## Pull request testing ##
###########################
###########################
name: Hackathon Pull Request

# Documentation:
# - Workflow: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - SuperLinter: https://github.com/github/super-linter
# - Markdown linter: https://github.com/DavidAnson/markdownlint
# - Link validation: https://github.com/remarkjs/remark-validate-links

######################################################
# Start the job on a pull request to the hackathon-test branch #
######################################################
on:
  pull_request:
    branches: [hackathon-test]
    paths:
      - 'src/pages/**'

###############
# Set the Job #
###############
jobs:
  call_reusable_workflow:
    name: Generate AI Metadata
    # Skip if PR title starts with "[AI PR] Metadata Update" or branch name starts with "ai-metadata"
    if: >-
      !startsWith(github.event.pull_request.title, '[AI PR] Metadata Update') ||
      !startsWith(github.event.pull_request.head.ref, 'ai-metadata')
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/ai-pr-request-metadata.yml@app-builder-test
    with:
      PR_ID: ${{ github.event.pull_request.number }}
      FILE_NAME: "pr_content.txt"
    secrets:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
