---
    name: Build Contributors
    on:
      pull_request:
      workflow_dispatch:
    
    jobs:
      build-contributors:
        name: Build Contributors
        uses: AdobeDocs/adp-devsite-workflow/.github/workflows/build-contributors.yml@main
        secrets: inherit
