---
name: Reuse Deployment
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment to deploy to"
        type: choice
        required: true
        default: "stage"
        options:
          - stage
          - prod
      baseSha:
        description: "Use base SHA commit to deploy from (empty string defaults to last commit before HEAD)"
        type: string
        required: false
        default: ""

jobs:
  reuse_deployment:
    name: Reuse Deployment
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/deploy.yml@main
    with:
      env: ${{ inputs.env }}
      baseSha: ${{ inputs.baseSha }}
